//go:build ignore

// gen-asset-hashes walks static/ and writes asset_hashes_gen.go with
// precomputed content hashes for production builds (no runtime SHA256 per request).
//
// Usage: go run scripts/gen-asset-hashes.go
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root := "static"
	if len(os.Args) > 1 {
		root = os.Args[1]
	}

	hashes := map[string]string{}
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)
		if !strings.HasSuffix(rel, ".css") && !strings.HasSuffix(rel, ".js") {
			return nil
		}
		sum, hashErr := hashFile(path)
		if hashErr != nil {
			return hashErr
		}
		hashes[rel] = sum
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-asset-hashes: %v\n", err)
		os.Exit(1)
	}

	keys := make([]string, 0, len(hashes))
	for k := range hashes {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	out, err := os.Create("asset_hashes_gen.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-asset-hashes: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by scripts/gen-asset-hashes.go; DO NOT EDIT.")
	fmt.Fprintln(out, "package main")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "var precomputedAssetHashes = map[string]string{")
	for _, k := range keys {
		fmt.Fprintf(out, "\t%q: %q,\n", k, hashes[k])
	}
	fmt.Fprintln(out, "}")
}

func hashFile(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)[:6]), nil
}
